name: Update Files with Node.js
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate HTML files
      run: node generate-html.js

    - name: Commit and push HTML changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add *.html
        git commit -m 'Regenerate HTML pages' || echo "No changes to commit"
        git push
